server:
  port: 8080

# 应用配置
app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: '*'
    # SC 渠道配置 - 拼团对接渠道值、回调通知
    group-buy-market:
      api-url: http://127.0.0.1:8091
      notify-url: http://127.0.0.1:8080/api/v1/alipay/group_buy_notify
      source: s01
      chanel: c01

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# 数据库配置；启动时配置数据库资源信息
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:23306/s-pay-mall-ddd-market?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    pool-name: Retail_HikariCP
    minimum-idle: 15 #最小空闲连接数量
    idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
    maximum-pool-size: 25 #连接池最大连接数，默认是10
    auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
    max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
    connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
    connection-test-query: SELECT 1
  type: com.zaxxer.hikari.HikariDataSource

# MyBatis 配置【如需使用记得打开】
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# 微信公众号对接
weixin:
  config:
    originalid: gh_c0d3c03e11e6
    token: b8b6
    app-id: wx51f1d5483e65bbc5
    app-secret: 65c095fd1c7dd909f2102d22cfb28592
    template_id: FQZ8m_W6ya2JWj-MJu0hvpTdJPqKJ4yYt05gugyLyF4

# 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
alipay:
  enabled: true
  app_id: 9021000151620143
  merchant_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC6LMtpqaZ/ApQvMPbK4U4AKDSbSRD+S9KBnbfE3MJDVs73/FcXftY4e9jzMa1ETd6Gl7/Sgtfo22jfZcH2UPLn9YsBKjfEGUo1Xlu1hAA077oK+8A8DWlGxH252XMVyXvKE3nyElcGqqJUBEAoIk/KKqKGISvl+y0uOW3GcSzFOAigzse4JrTake5yAeLisllqjtEqv7JPfr/5H74wbjXh9j0bzxbBGSjd/Hxdl2opxdDbiymQ0z9qorKRlVX7L4SyroGdZctIDs/Ry/q1EZpBBb89yi2eCwLbZGNMAsliKeuHyvBd5FWeV9Tj96AWAUrzEIJ8s4a0dtANzp4lpypLAgMBAAECggEBALheRe7Un9plrmPxhGUzq/AB4N7rA9YhNk0/6E4fJI5VOE9i6MiOxgxXsWhdCK58wuLdAoyxIKosJnYdKnEIhxTpGAhGS8V6GgAx+nYOS7ogsUfROfT+fwQi8DMNQagQyPM8SGZOfTpP3sN/Fh3opMWbZSmZTgTJslt1ad28FE8U1iSVIucznwzsnFk9FNogLOVmGo3o6otqcJhaF5WoDHkiaxF9EKGDgAoqx8HF+mwhWo69Ok9dLUIyaHun1KsbI2RirmxVbnyiiflBBUHgjv26dzxIfqdvSaDJH9ePs9TkijAxryQQunG90K7gVkO2VxJHRZPAUiQ33xwYeppiupECgYEA6dBLI8YNfTgvhhwGaIXWVLrBHJWqc8TrLiFmuAXH3V+lMM3eR7rv5Fgr9Id5LSph+ABGb1/ftKAm2AXkXi+qvxeMKM/H0t6s5NSYbHEVEsyL0GN/0kkNK0XeselVoUcN+VRlKQNaRd1U0DyNn3bVdGbknWbW5oRgNLwSQYIJdWkCgYEAy9dIJeQV7z1D7HLVnVpyALJU+iqr0pd6lt5l5Qe1CdL1Lzyu3leUFvATSX/wvfMksYSY9RJpTUSA2kPuqH3fXdMvTiMlRDBHPzlZwoSzO8d6W/IkyziZeZA70oYwtAKKoq5rDhtKThkveH4OZUC7/FE9X5Wx0BlkS7JENusv55MCgYEA0xLJsmrJpKBDLsM/+b3Qxj6ttHtcHBTJ5qQakcgOLMd6XfuLTZ/xjmcWjzJ5bw+Sz4qYC1U2o13skxmGloxbjRTZ38Hrd260EAPn8gWH66eiFCauroxqCgWSS3QEbIqzj8DjbcnsBaQQO8heZXWmruVwPrQnDoS0QQcDSAX3OfkCgYAoKqnK3aD83YOu6gnx0cq5HGrmSNZGzxaW+Af4E4a3AtzRjBGhOnyx8Gi8iPt1Up4eZNSHJjOdyCvj1pMGnJcRM/YUXZSQVTsU2EY5sFBpLSuNRq+9Y8/KRoOjPlIGhqGu4NOzmekQbqIOCjjn9tOUKqX/Wc4KBZbf26bZc4qjBQKBgDf72QlBktQHpUqjmrFkjtRhS1LGbva2PnsYJGK6jjXd9gwAFExlqUh42K1Cog5BfR76OUKhhSBH3T02sel0dr3DoJY88B2mGp1WK9kbkag6pPPuV89pFEgdBINlbo8gmY84NwXN3EINoONm5/wanrn3mbudendIEOXT0bFKhcRu
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlClnJeSDnZzeiAfXdtr6uUA8m1ro1RiPeqHh/F+2LjoVj66vkJbDHb7XNR0b3Lf/em93gXNNBoffoTnon8AgjzTG1vPG2/9WStE+zvxPPrBn/ZNhLWRtoKDtbSAIUKEjttexsvW+17hyooXayc4qR7ONex/IVPyOOFPxKYqKF3RC0UL2/W/mS86JoECWb4fcm11Zz017KPBjvzZKXgYr6yyJUbRd54Xz9WS/gJ912R9VSfn0M8drrpIxCTkszb5ayO6XQmWe44v6CzSAr9ZJysh6HxJxtvztk8X6jD8f3HGXmn+osZ8lLHLzC9BRKOwUqOOQQMumy44oTc4KWxTwuwIDAQAB
  notify_url: http://whxxlkx.natapp1.cc/api/v1/alipay/alipay_notify_url
  return_url: http://localhost:63342/s-pay-mall-ddd-market/docs/dev-ops/nginx/html/index.html
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do

# SC 渠道配置 - 拼团对接渠道值
sc:
  group:
    buy:
      market:
        source: s01
        chanel: c01

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml