server:
  port: 8080

# 应用配置
app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: '*'
    # SC 渠道配置 - 拼团对接渠道值、回调通知
    group-buy-market:
      api-url: http://127.0.0.1:8091
      notify-url: http://127.0.0.1:8080/api/v1/test/group_buy_notify
      source: s01
      chanel: c01

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# 数据库配置；启动时配置数据库资源信息
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://mysql:3306/s-pay-mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    pool-name: Retail_HikariCP
    minimum-idle: 15 #最小空闲连接数量
    idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
    maximum-pool-size: 25 #连接池最大连接数，默认是10
    auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
    max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
    connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
    connection-test-query: SELECT 1
  type: com.zaxxer.hikari.HikariDataSource

# MyBatis 配置【如需使用记得打开】
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# 微信公众号对接
weixin:
  config:
    originalid: gh_e067c267e056
    token: b8b6
    app-id: wx5a228ff69e28a91f
    app-secret: 0bea03aa1310bac050aae79dd8703928
    template_id: RbEZ2jo47dQmF4A7_Ku7RsDy1x_5by6bk1Ox6rPCl4Y

# 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
alipay:
  enabled: true
  app_id: 9021000132689924
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCP1O8TRLFyMODdMY1SLx56dJlol/MERVNQqFE3uZI0fOMuII4ZcAoU0cqVtDZiGgvR4sOvfVjSMoVDgp+Co3Vg49VLT5y5D+IMNH/9AhWWWh8oc2aLStAuIiehLr0w6S5K90+yyB/pPBYsioTdWAHrw28UV1iQDJexiOPT3GRLvRrzLVXU2Sk6oKGOazxW9IG0oYHGELxN4KO6FShEb+8I2dH1bR869G7cxcEpS7sKPpnNfkfitJtZjonNqVOgNmIbhAPzA+AOXfAEKCdoCenlCBv+MjHLRguDz+zKqMsdSHe8xoTVd6zlOfAyNlKkELneT+937nsj442bxF6Zpv09AgMBAAECggEAZ3lc9ZO5xNj9LKR1cuaLGrW/l8uY/T2SjrhIlbpfQHuIRKsPD6XW2tuCzuhzJ2htkHV/KkUXHUFTNhpG/wjxbN77l86ShWCz0uwCF9bkCOKU/9jlsNgFpOrVb9PcL8/RigUZxRjMPFMJ8MlGhKbH2wEibJPaFue4SfSdUtF/Jiy1haPje+KOcALPEsE2lwltiQe7vpXkO7bKwxMdWprahw6ERRAlGXN+whPydNZnT6nwVnRo2wWZ6k691FZPMvsJrsPnplZJ6gCx5GKrTdfAe68cizKYmOHYghfTnG+JrwDUk51dCMYfx/RoahdVVMqgXtRdU17afLgjhACBp2TAAQKBgQDEjXAIDq2BQVtRlwT+1DmxmLLrm3N5Tw+t+RExL3MDTjDVTyvAq24Dbv48nTMwyyscTs5h+rTnm00etLYgXHYzxkG99yH5G4ESxMrejKMwH4JJfwB/0eKZ+RwlzafrEJiewMr1s43yMIO8kFMzwu3+EYDQOlsVOrOE4b6+GO+BPQKBgQC7VXbinVP5taGqddhM4uEDZUqVWauPIgcdAvGWtMW6Inhy7rqXm30qkVyi7Xp9vzBVNEvHJ8ujEEi3EzGZ24KEgO1GQQviICHjJjBv1u6sSYg1yGm7HuI1d8L4otpmTTi+ZeUZKnP9C7HVjfNelIMHVIw/ti32BIoDlBnLdpUsAQKBgQC3qY5RCR4Z1K93Gw4A7OCIUi6GODj71uPI5h6pfjQTl6HMAPHaVJY1QSbyDtaBtqcvCXiSV4lpjlXO5n/011FgadaOovos4wWGOztyH6pxUlAVS0Z1KfN7eypRLM3GujhSx8YfN0vhTnIa5iXJDVIEAekDKjRoLvUGq0boLTbH5QKBgHwqQ2gkezpxZrwC6+DaJ+YGRw8CpjFyjmBuSQ5otv2OR2N2U/qUtrt2KX5cBOo/xJtU1D0mZVSpQGkHscKWucV1Zs8/4c55Gbzi3Qvj28IZ4swzD9FUwP5LaNE/r55K5KdeBiFOAB7il3ZCZeJ0cPx0z5iS+ZesnoWMriQrbugBAoGAXwMG2w2ONic3y2jpuOgdbr4s5jv1PYqkx2LELPDaE1mLkAqFTHr+3vYOukMqzHL+v4H9AdR5Iu4Bo3rgPZjlCOkQ7RinFVig66MeKMNVM1irKYaaEVur1xjSpYWvvWg1+cIL9gaNMFcNqsRUtG9U9FqBLrDn1gA4lfDlu02Ttzg=
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmgtSO8GV5YSl01AWgGWe2xKJ9oDfjzf5vNtJS6SSc5klmGMToVdsi3gmLipN04yzmnEEchmFxsuxKLLhdQuC4d9V74I6CVIZPPHtaSuz/T3EZTHtQIGwF705Yrq1bd63l70iTfkrS0Ry9f72SDZEBBLllXfFo+otChwRRN+UXDd8X/bplV3/cbRncV5yWRnHHCgzQiwpH3ilS+sOmMfdfac0bi/xB7HIU6nUX04VCjAR7itSr0OmU8HC6p20Ubvjs45R6VuR7FMI+OahCd3LDe/ayelScfQ4zavruk4HGx3TDH4hLDA3N+xid5Cu5erLDPHtFXfnQHI4n/opQaXo5wIDAQAB
  notify_url: http://xfg-studio.natapp1.cc/api/v1/alipay/alipay_notify_url
  return_url: https://nuaa.edu.cn
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml